# Generated by Django 6.0.6 on 2026-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudoapp', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
